### ISSUE TITLE
Not able to do production build

### ISSUE THREAD

**Issue by shashi97** [strongloop/loopback4-example-getting-started#10] opened 2017-11-30 07:21 UTC
I have a query that should be on discussion page but just asking here

I have completed my app in LB4 and the next phase production i run a command npm run build but its build in dist file with .map files i think that is not production build so what i need to do there is no proper documentation is available so i'm asking here

thanks in advance

**Comment by kjdelisle** [comment] 2017-11-30 19:49
@shashi97 Are you using `@loopback/build` for your tsconfig, or did you go with the alternative when generating your project?

**Comment by virkt25** [comment] 2017-11-30 19:50
Hi @shashi97, if you're looking to disable source maps you can do so by adding the following in your `tsconfig.json` in the project root.

```
"compilerOptions": {
    "sourceMap": false
}
```

**Comment by kjdelisle** [comment] 2017-11-30 19:54
Building off @virkt25 's suggestion, you can create a separate command in your scripts section of the package.json to switch between build types:

```
"scripts": {
  "build:prod": "lb-tsc -p tsconfig.prod.json",
  "build": "lb-tsc",
  // etc...
}
```

And then have a tsconfig.prod.json file:
```json
{
    "extends": "./tsconfig.json",
    "compilerOptions": {
      "sourceMap": false
    }
}

```

**Comment by shashi97** [comment] 2017-11-30 20:30
this is my tsconfig.json
{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noUnusedLocals": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "target": "es6",
    "outDir": "dist",
    "sourceMap": true
  }
}

**Comment by kjdelisle** [comment] 2017-11-30 20:39
@shashi97 Here's a more fleshed out example:

### package.json
**Note: The prod build command will delete the dist folder (to clean up old .map.js files)** 
```json
{
  "name": "your-app",
  "version": "1.0.0",
  "description": "your app",
  "keywords": [
    "loopback-application",
    "loopback"
  ],
  "main": "index.js",
  "engines": {
    "node": ">=8"
  },
  "scripts": {
    "build:prod": "rm -rf dist && lb-tsc -p tsconfig.prod.json",
    "build": "lb-tsc",
    "build:watch": "lb-tsc --watch",
    "clean": "lb-clean",
    "lint": "npm run prettier:check && npm run tslint",
    "lint:fix": "npm run prettier:fix && npm run tslint:fix",
    "prettier:cli": "lb-prettier \"**/*.ts\" \"**/*.js\"",
    "prettier:check": "npm run prettier:cli -- -l",
    "prettier:fix": "npm run prettier:cli -- --write",
    "tslint": "lb-tslint",
    "tslint:fix": "npm run tslint -- --fix",
    "pretest": "npm run clean && npm run build",
    "test": "lb-dist mocha DIST/test",
    "posttest": "npm run lint",
    "start": "npm run build && node .",
    "prepare": "npm run build:prod"
  },
  "license": "MIT",
  "files": [
    "README.md",
    "index.js",
    "index.d.ts",
    "dist",
    "dist6"
  ],
  "dependencies": {
    "@loopback/context": "^4.0.0-alpha.18",
    "@loopback/core": "^4.0.0-alpha.22",
    "@loopback/rest": "^4.0.0-alpha.7"
  },
  "devDependencies": {
    "@loopback/build": "^4.0.0-alpha.4",
    "@loopback/testlab": "^4.0.0-alpha.13",
    "@types/mocha": "^2.2.43",
    "mocha": "^4.0.1"
  }
}
```

### tsconfig.json
```json
{
  "$schema": "http://json.schemastore.org/tsconfig",
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noImplicitAny": true,
    "strictNullChecks": true,

    "lib": ["es2017", "dom"],
    "module": "commonjs",
    "moduleResolution": "node",
    "target": "es6",
    "sourceMap": true,
    "declaration": true
  }
}
```

### tsconfig.prod.json
```
{
    "extends": "./tsconfig.json",
    "compilerOptions": {
      "sourceMap": false
    }    
}
```

### Regular Build
```
npm run build
```

### Production Build
```
npm run build:prod
```

**Comment by kjdelisle** [comment] 2017-11-30 21:59
@shashi97 Please let me know if this was helpful, so I can close this issue.

**Comment by shashi97** [comment] 2017-12-01 13:26
thanks @kjdelisle for your response

I do all the things but not able produce prod build after running command npm run build:prod not happening here  only its removed dist file and nothing going next.


```
E:\Projects\property-portal\property-portal\property-portal-api>npm run build:prod
> loopback4-example-getting-started@1.0.0 build:prod E:\Projects\property-portal\property-portal\property-portal-api
> rimraf dist && lb-tsc -p tsconfig.prod.json


E:\Projects\property-portal\property-portal\property-portal-api>
```



this is my package.json ---

```
{
  "name": "loopback4-example-getting-started",
  "version": "1.0.0",
  "description": "An application and tutorial on how to build with LoopBack 4.",
  "main": "dist/index.js",
  "engines": {
    "node": ">=8"
  },
  "scripts": {
    "start": "npm run build && node .",
    "build:prod": "rimraf dist && lb-tsc -p tsconfig.prod.json",
    "build": "lb-tsc && lb-tslint",
    "test": "npm run build && mocha \"./dist/test/**/*.test.js\""
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/strongloop/loopback4-example-getting-started.git"
  },
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/strongloop/loopback4-example-getting-started/issues"
  },
  "homepage": "https://github.com/strongloop/loopback4-example-getting-started#readme",
  "dependencies": {
    "@loopback/core": "^4.0.0-alpha.16",
    "@loopback/repository": "^4.0.0-alpha.10",
    "@loopback/rest": "^4.0.0-alpha.3",
    "@types/sinon": "^2.3.6",
    "async-file": "^2.0.2",
    "cors": "^2.8.4",
    "express": "^4.16.2",
    "jsonwebtoken": "^8.1.0",
    "loopback-connector-mssql": "^3.1.0",
    "sinon": "^4.0.1"
  },
  "files": [
    "README.md",
    "index.js",
    "index.d.ts",
    "dist",
    "dist6"
  ],
  "devDependencies": {
    "@loopback/build": "^4.0.0-alpha.3",
    "@loopback/testlab": "^4.0.0-alpha.9",
    "@types/cors": "^2.8.3",
    "@types/mocha": "^2.2.43",
    "@types/node": "^8.0.34",
    "mocha": "^4.0.1",
    "typescript": "^2.6.1"
  }
}
```


this is my tsconfig.json---
```
{
  "$schema": "http://json.schemastore.org/tsconfig",
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noUnusedLocals": true,
    "lib": ["es2017", "dom"],
    "module": "commonjs",
    "moduleResolution": "node",
    "target": "es6",
    "outDir": "dist",
    "sourceMap": true
  }
}
```

tsconfig.prod.json--

```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "sourceMap": false
  }
}
```

**Comment by kjdelisle** [comment] 2017-12-01 13:36
Would you be able to make a sample repository for us to view? It's difficult to debug the problem by guessing what you might be missing.

**Comment by shashi97** [comment] 2017-12-01 14:20
this is my public repository may be you need to changes db.datasource inside datasources for data database connection 
https://github.com/shashi97/loopback-4-property-portal.git

**Comment by kjdelisle** [comment] 2017-12-01 16:26
@shashi97 So, I think the problem is that when you run `npm start`, it's running the regular build command, which will put all of those map files back in place. In this case, you can:
- change the `start` script to not call `npm run build`
- change the `start` script to instead call `npm run build:prod`
- make a new `start:dev` command and have it use `npm run build && node .`, then change the `start` script to run `node .` (this one is my personal choice, since you'll probably want to start the app in either "mode" at some point)

**Comment by shashi97** [comment] 2017-12-06 08:13
@kjdelisle the question is when i go to dist folder after prod build, when i run node . the error massage in console is that loopback/core not found and when i inspect the prod build files  i  found that there is no bundling files that have all minified js of node module(may be i'm wrong i don't know how this will work but) like see there is only my controllers and repository is there, so i can't run that app.
or i need to put node_module and package.json along with dist ?

**Comment by kjdelisle** [comment] 2017-12-07 14:59
@shashi97 In our scaffolded application setup, the "top-level" runnable file is still `./index.js`. This is because we still need to have the `node_modules` folder at root level. This also means that the `./dist` folder should be looking for your `node_modules` folder in the same location that you use it in when in development.

Our production build script does _not_ provide any minification, as this would be too opinionated and is not the concern of the LoopBack framework. If you intend to minify your code, you'll need to write your own script or hook in an existing minifier script and call it as the last step in your production build (ex. `"build:prod": "lb-tsc -p tsconfig.prod.json && ./my-minify-script.sh")

To help you with this, I would need to see the repository you're working with as there are too many variables at play here to guarantee that I can point out what's missing.

**Comment by kjdelisle** [comment] 2017-12-11 16:22
@shashi97 I'm going to close this issue, since it's specific to your own implementation. Reach out on our [Gitter page](https://gitter.im/strongloop/loopback) if you still need help. :)

**Closed as completed by kjdelisle** 2017-12-11 16:22 UTC
Labels: team-apex
